openapi: 3.0.3
info:
  title: Linwood Bucket
  description: Service to publish resources.
  version: "1.0"

paths:
  /index.json:
    get:
      summary: Returns default information about this service.
      description: This can be useful to check if an api version is maintained.
      responses:
        '200':
          description: The configuration of the service
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    example: "1.0"
                    type: string
                    title: The version of the generator
                  updated:
                    title: The version code in unix epoch time
                    example: 1640991600
                  name:
                    title: The name of the bucket
                    example: TestBucket
                  description:
                    title: The description of the bucket
                    example: This is an example bucket
                  api-versions:
                    type: array
                    items:
                      type: string
                      example: [ "0" ]
